[platformio]
default_envs = nodemcuv2

[env:native]
platform = native
test_framework = custom
test_filter = test_native_*
build_flags =
  -std=gnu++17
  -Wall
  -Wextra

[env:nodemcuv2]
platform = espressif8266@4.2.1
board = nodemcuv2
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
  sparkfun/SparkFun MAX3010x Pulse and Proximity Sensor Library@1.1.2
  milesburton/DallasTemperature@4.0.6
  paulstoffregen/OneWire@2.3.8
  knolleary/PubSubClient@2.8
  bblanchon/ArduinoJson@7.4.3
build_flags =
  -Wall
  -Wextra
  -D ENABLE_LOCAL_BUZZER=0
  -D ENABLE_LOCAL_ACK_BUTTON=0
  -D ENABLE_BUILTIN_LED=1
